### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by dudeinthemirror** [matt-oakes/react-native-boilerplate#15]
@matt-oakes Thanks for putting this boilerplate together. I am trying to use it but I'm encountering the following error when trying to ignite (also the last `yarn install` hangs):

<img width="1324" alt="screen shot 2018-01-22 at 8 18 15 am" src="https://user-images.githubusercontent.com/981638/35231342-5f224bd4-ff4d-11e7-9abf-a9d9030afad6.png">

Here is my environment:
> react-native --version
react-native-cli: 2.0.1
react-native: 0.50.4

> yarn --version
1.3.2

> npm --version
5.6.0

> ignite --version
2.0.0

Thanks for your time!

**Comment by matt-oakes** [comment]
It looks like the issues is that the `bundle install` command is failing. This is part of the `postinstall` task in `package.json`. You should be able to fix this by doing:

`[sudo] gem install bundler`

Just a note that I would strongly recommend again using this boilerplate. It's really only intended for my own use. It is pretty opinionated and is unlikely to be well supported. Instead, I would recommend the [official boilerplate](https://github.com/infinitered/ignite-ir-boilerplate).

**Comment by dudeinthemirror** [comment]
Roger that, thanks for letting me know Matt!

**Comment by matt-oakes** [comment]
No problem! You're welcome to use it if it suits you better than the official boilerplate, but it wont be anywhere near as well maintained.

I'll add a note to the readme to mention this.

Thanks 👍
